id: ID79CFED1
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:07:28.370125+00:00
last_modified: 2022-12-14 18:07:28.370134+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-09-04T08:54:59.295Z'
  creationid: esukhia
  eft-text-id: UT22084-040-003
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_52-The_Indivisible_Nature-v1
bases:
  1B7F:
    source_metadata: null
    order: 1
    base_file: 1B7F.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
